# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('game_key', models.CharField(max_length=256)),
                ('game_code', models.CharField(max_length=8)),
                ('game_start_datetime', models.DateTimeField(auto_now_add=True)),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=8)),
                ('exact', models.IntegerField(default=0)),
                ('near', models.IntegerField(default=0)),
                ('guess_datetime', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='core.Game')),
            ],
        ),
    ]
